---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      package:
        update_cache: yes
      changed_when: False
  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/packages_arch.yml
      when: ansible_distribution == "Archlinux"
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/dotfiles.yml
      when: ansible_distribution == "Archlinux"
    - include_tasks: tasks/doom-emacs.yml

  handlers:
    - name: enable lightdm
      systemd: name=lightdm enabled=yes
