- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      package:
        update_cache: yes
      changed_when: False
  tasks:
    - include: tasks/users.yml
    - include: tasks/packages_arch.yml
      when: ansible_distribution == "Archlinux"
    - include: tasks/cron.yml
    - include: tasks/dotfiles.yml
      when: ansible_distribution == "Archlinux"
