---

- name: Install Python-pip
  become: yes
  pacman: name=python-pip state=present

- name: Create bin, share and src directory in home/.local
  become: yes
  become_user: lydien
  file:
    path: /home/lydien/.local/{{ item }}
    state: directory
  with_items:
    - bin
    - share
    - src
    - share/applications

- name: Install konsave
  become: yes
  become_user: lydien
  pip: name=konsave state=present

- name: Install git LFS
  become: yes
  pacman: name=git-lfs state=present

- name: Git LFS pull konsave configuration
  become: yes
  become_user: lydien
  shell: |
    git lfs install
    git lfs pull

- name: launch konsave to install KDE configuration
  become: yes
  become_user: lydien
  shell: |
    /home/lydien/.local/bin/konsave -i /home/lydien/.local/share/aritim-dark.knsv
    /home/lydien/.local/bin/konsave -a aritim-dark

- name: Install desktop files from jumpapp
  become: yes
  become_user: lydien
  shell: |
    for entry in /usr/share/applications/{emacs,chromium,org.kde.konsole}.desktop; do
        target=~/".local/share/applications/$(basename "$entry")"
        jumpappify-desktop-entry "$entry" >"$target"
    done
