---

- name: Clone dotfiles git repo and install
  git:
    repo: https://github.com/zedxlucian/dotfiles
    version: master
    dest: /home/lydien/dotfiles

- name: Prepare Desktop environment for stow
  file:
    path: /home/lydien/.config/{{ item }}
    state: absent
  with_items:
    - user-dirs.dirs
    - user-dirs.locale

- name: Stow dotfiles
  shell: |
    cd /home/lydien/dotfiles
    stow config home

- name: Change shell to zsh
  expect:
    command: chsh -s /bin/zsh
    responses:
      (?i)password: "{{ lydien_password }}"

- name: Export zsh default dir system-wide
  become: yes
  copy:
    src: files/zshenv
    dest: /etc/zsh/zshenv
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Create dir for zsh history in .cache folder
  become: yes
  become_user: lydien
  file:
    path: /home/lydien/.cache/zsh
    state: present
