---

- name: Clone dotfiles git repo and install
  git:
    repo: https://github.com/zedxlucian/dotfiles
    version: master
    dest: /home/lydien/dotfiles

- name: Stow dotfiles
  shell: |
    cd /home/lydien/dotfiles
    stow config home

- name: Change shell to zsh
  expect:
    command: chsh -s /bin/zsh
    responses:
      (?i)password: "{{ lydien_password }}"
