---

- name: Install base-devel to be able to install aur packages
  become: yes
  pacman: state=present name=base-devel

- name: Clone yay repo from Archlinux
  become: yes
  git: repo=https://aur.archlinux.org/yay.git dest=/opt

- name: Give ownership to yay repo to user
  become: yes
  file:
    path: /opt/yay
    owner: lydien
    group: users
    recurse: yes

- name: Install yay
  shell: |
    cd /opt/yay && makepkg -si --noconfirm

- name: Install packages from pacman
  become: yes
  pacman:
    state: present
    name:
      - plasma
      - dosfstools
      - dunst
      - exfat-utils
      - sxiv
      - nitrogen
      - man-db
      - noto-fonts-emoji
      - noto-fonts-cjk
      - ntfs-3g
      - maim
      - socat
      - unrar
      - unzip
      - youtube-dl
      - poppler
      - mediainfo
      - atool
      - fzf
      - fd
      - ripgrep
      - shellcheck
      - mlocate
      - neovim
      - emacs
      - mpv
      - exa
      - neofetch
      - terminus-font
      - ttf-roboto
      - ttf-roboto-mono
      - pacman-contrib
      - editorconfig-core-c
      - pandoc
      - graphviz
      - npm
      - qemu
      - virt-manager
      - virt-viewer
      - dnsmasq
      - vde2
      - bridge-utils
      - openbsd-netcat
      - iptables
      - cronie
      - chromium
      - stow

- name: Install zsh-autosuggestions from AUR
  shell: |
    yay -S zsh-autosuggestions zsh-fast-syntax-highlighting betterlockscreen arc-gtk-theme-git --noconfirm
