---
- name: Install base-devel to be able to install aur packages
  become: yes
  pacman: state=present name=base-devel

- name: Install login manager lightdm
  become: yes
  pacman: state=present name=lightdm,lightdm-slick-greeter

- name: Use lightdm-slick-greeter as default greeter for lightdm
  become: yes
  shell: |
    sed -i '/\[Seat\:\*\]/a greeter-session=lightdm-slick-greeter' /etc/lightdm/lightdm.conf
  notify: enable lightdm

- name: Install packages from pacman
  become: yes
  pacman:
    state: present
    name:
      - xfce4
      - xfce4-goodies
      - dosfstools
      - dunst
      - exfat-utils
      - sxiv
      - nitrogen
      - man-db
      - noto-fonts-emoji
      - noto-fonts-cjk
      - ntfs-3g
      - maim
      - socat
      - unrar
      - unzip
      - youtube-dl
      - poppler
      - mediainfo
      - atool
      - fzf
      - fd
      - ripgrep
      - shellcheck
      - mlocate
      - neovim
      - emacs
      - mpv
      - exa
      - neofetch
      - terminus-font
      - ttf-roboto
      - ttf-roboto-mono
      - pacman-contrib
      - editorconfig-core-c
      - pandoc
      - graphviz
      - npm
      - qemu
      - virt-manager
      - virt-viewer
      - dnsmasq
      - vde2
      - bridge-utils
      - openbsd-netcat
      - iptables
      - cronie
      - firefox

- name: Install packages from AUR
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
      - zsh-autosuggestions
      - zsh-fast-syntax-highlighting
      - i3lock-color-git
      - betterlockscreen
      - arc-gtk-theme-git
