---
- name: Create group users
  group: name=users state=present

- name: Create lydien user
  user:
    name: lydien
    create_home: yes
    group: users
    shell: /usr/bin/zsh
  when: ansible_distribution == "Archlinux"

- name: copy sudoers_lydien
  copy:
    src: sudoers_lydien
    dest: /etc/sudoers.d/lydien
    owner: root
    group: root
    mode: 0440

- name: Setting git configuration for user:lydien
  copy:
    src: git_config_lydien
    dest: /home/lydien/.gitconfig
    owner: lydien
    group: users
    mode: '0644'

- name: Create aur_builder user to install AUR packages
  user:
    name: aur_builder
    create_home: yes
    group: users

- name: Add aur_builder as sudoer
  lineinfile:
    path: /etc/sudoers.d/11-installer-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  when: ansible_distribution == "Archlinux"

- name: create ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  copy:
    src: sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
